// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MoodSelectorController from "./mood_selector_controller"
application.register("mood-selector", MoodSelectorController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import MoodFormController from "./mood_form_controller"
application.register("mood-form", MoodFormController)
