// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MoodSelectorController from "./mood_selector_controller"
application.register("mood-selector", MoodSelectorController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import ToggleFormController from "./toggle_form_controller"
application.register("toggle-form", ToggleFormController)

import AmountController from "./amount_controller"
application.register("amount", AmountController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ThemeToggleController from "./theme_toggle_controller"
application.register("theme-toggle", ThemeToggleController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import ParallaxController from "./parallax_controller"
application.register("parallax", ParallaxController)
